// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cusf/common/v1/common.proto
// Protobuf C++ Version: 6.30.1

#ifndef cusf_2fcommon_2fv1_2fcommon_2eproto_2epb_2eh
#define cusf_2fcommon_2fv1_2fcommon_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/wrappers.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cusf_2fcommon_2fv1_2fcommon_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cusf_2fcommon_2fv1_2fcommon_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cusf_2fcommon_2fv1_2fcommon_2eproto;
}  // extern "C"
namespace cusf {
namespace common {
namespace v1 {
class ConsensusHex;
struct ConsensusHexDefaultTypeInternal;
extern ConsensusHexDefaultTypeInternal _ConsensusHex_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ConsensusHex_class_data_;
class Hex;
struct HexDefaultTypeInternal;
extern HexDefaultTypeInternal _Hex_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Hex_class_data_;
class ReverseHex;
struct ReverseHexDefaultTypeInternal;
extern ReverseHexDefaultTypeInternal _ReverseHex_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ReverseHex_class_data_;
}  // namespace v1
}  // namespace common
}  // namespace cusf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cusf {
namespace common {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class ReverseHex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cusf.common.v1.ReverseHex) */ {
 public:
  inline ReverseHex() : ReverseHex(nullptr) {}
  ~ReverseHex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReverseHex* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReverseHex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReverseHex(::google::protobuf::internal::ConstantInitialized);

  inline ReverseHex(const ReverseHex& from) : ReverseHex(nullptr, from) {}
  inline ReverseHex(ReverseHex&& from) noexcept
      : ReverseHex(nullptr, std::move(from)) {}
  inline ReverseHex& operator=(const ReverseHex& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReverseHex& operator=(ReverseHex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReverseHex& default_instance() {
    return *reinterpret_cast<const ReverseHex*>(
        &_ReverseHex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ReverseHex& a, ReverseHex& b) { a.Swap(&b); }
  inline void Swap(ReverseHex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReverseHex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReverseHex* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReverseHex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReverseHex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReverseHex& from) { ReverseHex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReverseHex* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cusf.common.v1.ReverseHex"; }

 protected:
  explicit ReverseHex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReverseHex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReverseHex& from);
  ReverseHex(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReverseHex&& from) noexcept
      : ReverseHex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHexFieldNumber = 1,
  };
  // .google.protobuf.StringValue hex = 1 [json_name = "hex"];
  bool has_hex() const;
  void clear_hex() ;
  const ::google::protobuf::StringValue& hex() const;
  [[nodiscard]] ::google::protobuf::StringValue* PROTOBUF_NULLABLE release_hex();
  ::google::protobuf::StringValue* PROTOBUF_NONNULL mutable_hex();
  void set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  ::google::protobuf::StringValue* PROTOBUF_NULLABLE unsafe_arena_release_hex();

  private:
  const ::google::protobuf::StringValue& _internal_hex() const;
  ::google::protobuf::StringValue* PROTOBUF_NONNULL _internal_mutable_hex();

  public:
  // @@protoc_insertion_point(class_scope:cusf.common.v1.ReverseHex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReverseHex& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE hex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cusf_2fcommon_2fv1_2fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ReverseHex_class_data_;
// -------------------------------------------------------------------

class Hex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cusf.common.v1.Hex) */ {
 public:
  inline Hex() : Hex(nullptr) {}
  ~Hex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Hex* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Hex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Hex(::google::protobuf::internal::ConstantInitialized);

  inline Hex(const Hex& from) : Hex(nullptr, from) {}
  inline Hex(Hex&& from) noexcept
      : Hex(nullptr, std::move(from)) {}
  inline Hex& operator=(const Hex& from) {
    CopyFrom(from);
    return *this;
  }
  inline Hex& operator=(Hex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Hex& default_instance() {
    return *reinterpret_cast<const Hex*>(
        &_Hex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Hex& a, Hex& b) { a.Swap(&b); }
  inline void Swap(Hex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Hex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Hex* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Hex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Hex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Hex& from) { Hex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Hex* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cusf.common.v1.Hex"; }

 protected:
  explicit Hex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Hex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Hex& from);
  Hex(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Hex&& from) noexcept
      : Hex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHexFieldNumber = 1,
  };
  // .google.protobuf.StringValue hex = 1 [json_name = "hex"];
  bool has_hex() const;
  void clear_hex() ;
  const ::google::protobuf::StringValue& hex() const;
  [[nodiscard]] ::google::protobuf::StringValue* PROTOBUF_NULLABLE release_hex();
  ::google::protobuf::StringValue* PROTOBUF_NONNULL mutable_hex();
  void set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  ::google::protobuf::StringValue* PROTOBUF_NULLABLE unsafe_arena_release_hex();

  private:
  const ::google::protobuf::StringValue& _internal_hex() const;
  ::google::protobuf::StringValue* PROTOBUF_NONNULL _internal_mutable_hex();

  public:
  // @@protoc_insertion_point(class_scope:cusf.common.v1.Hex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Hex& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE hex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cusf_2fcommon_2fv1_2fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Hex_class_data_;
// -------------------------------------------------------------------

class ConsensusHex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cusf.common.v1.ConsensusHex) */ {
 public:
  inline ConsensusHex() : ConsensusHex(nullptr) {}
  ~ConsensusHex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ConsensusHex* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ConsensusHex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ConsensusHex(::google::protobuf::internal::ConstantInitialized);

  inline ConsensusHex(const ConsensusHex& from) : ConsensusHex(nullptr, from) {}
  inline ConsensusHex(ConsensusHex&& from) noexcept
      : ConsensusHex(nullptr, std::move(from)) {}
  inline ConsensusHex& operator=(const ConsensusHex& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConsensusHex& operator=(ConsensusHex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConsensusHex& default_instance() {
    return *reinterpret_cast<const ConsensusHex*>(
        &_ConsensusHex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ConsensusHex& a, ConsensusHex& b) { a.Swap(&b); }
  inline void Swap(ConsensusHex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConsensusHex* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConsensusHex* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ConsensusHex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConsensusHex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ConsensusHex& from) { ConsensusHex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ConsensusHex* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cusf.common.v1.ConsensusHex"; }

 protected:
  explicit ConsensusHex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ConsensusHex(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConsensusHex& from);
  ConsensusHex(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ConsensusHex&& from) noexcept
      : ConsensusHex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHexFieldNumber = 1,
  };
  // .google.protobuf.StringValue hex = 1 [json_name = "hex"];
  bool has_hex() const;
  void clear_hex() ;
  const ::google::protobuf::StringValue& hex() const;
  [[nodiscard]] ::google::protobuf::StringValue* PROTOBUF_NULLABLE release_hex();
  ::google::protobuf::StringValue* PROTOBUF_NONNULL mutable_hex();
  void set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  ::google::protobuf::StringValue* PROTOBUF_NULLABLE unsafe_arena_release_hex();

  private:
  const ::google::protobuf::StringValue& _internal_hex() const;
  ::google::protobuf::StringValue* PROTOBUF_NONNULL _internal_mutable_hex();

  public:
  // @@protoc_insertion_point(class_scope:cusf.common.v1.ConsensusHex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ConsensusHex& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE hex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cusf_2fcommon_2fv1_2fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ConsensusHex_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ConsensusHex

// .google.protobuf.StringValue hex = 1 [json_name = "hex"];
inline bool ConsensusHex::has_hex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.hex_ != nullptr);
  return value;
}
inline const ::google::protobuf::StringValue& ConsensusHex::_internal_hex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::StringValue* p = _impl_.hex_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::StringValue&>(::google::protobuf::_StringValue_default_instance_);
}
inline const ::google::protobuf::StringValue& ConsensusHex::hex() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.common.v1.ConsensusHex.hex)
  return _internal_hex();
}
inline void ConsensusHex::unsafe_arena_set_allocated_hex(
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hex_);
  }
  _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.common.v1.ConsensusHex.hex)
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE ConsensusHex::release_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* released = _impl_.hex_;
  _impl_.hex_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE ConsensusHex::unsafe_arena_release_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.common.v1.ConsensusHex.hex)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* temp = _impl_.hex_;
  _impl_.hex_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL ConsensusHex::_internal_mutable_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hex_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::StringValue>(GetArena());
    _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(p);
  }
  return _impl_.hex_;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL ConsensusHex::mutable_hex()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::StringValue* _msg = _internal_mutable_hex();
  // @@protoc_insertion_point(field_mutable:cusf.common.v1.ConsensusHex.hex)
  return _msg;
}
inline void ConsensusHex::set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hex_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.common.v1.ConsensusHex.hex)
}

// -------------------------------------------------------------------

// Hex

// .google.protobuf.StringValue hex = 1 [json_name = "hex"];
inline bool Hex::has_hex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.hex_ != nullptr);
  return value;
}
inline const ::google::protobuf::StringValue& Hex::_internal_hex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::StringValue* p = _impl_.hex_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::StringValue&>(::google::protobuf::_StringValue_default_instance_);
}
inline const ::google::protobuf::StringValue& Hex::hex() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.common.v1.Hex.hex)
  return _internal_hex();
}
inline void Hex::unsafe_arena_set_allocated_hex(
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hex_);
  }
  _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.common.v1.Hex.hex)
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE Hex::release_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* released = _impl_.hex_;
  _impl_.hex_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE Hex::unsafe_arena_release_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.common.v1.Hex.hex)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* temp = _impl_.hex_;
  _impl_.hex_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL Hex::_internal_mutable_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hex_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::StringValue>(GetArena());
    _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(p);
  }
  return _impl_.hex_;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL Hex::mutable_hex()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::StringValue* _msg = _internal_mutable_hex();
  // @@protoc_insertion_point(field_mutable:cusf.common.v1.Hex.hex)
  return _msg;
}
inline void Hex::set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hex_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.common.v1.Hex.hex)
}

// -------------------------------------------------------------------

// ReverseHex

// .google.protobuf.StringValue hex = 1 [json_name = "hex"];
inline bool ReverseHex::has_hex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.hex_ != nullptr);
  return value;
}
inline const ::google::protobuf::StringValue& ReverseHex::_internal_hex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::StringValue* p = _impl_.hex_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::StringValue&>(::google::protobuf::_StringValue_default_instance_);
}
inline const ::google::protobuf::StringValue& ReverseHex::hex() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.common.v1.ReverseHex.hex)
  return _internal_hex();
}
inline void ReverseHex::unsafe_arena_set_allocated_hex(
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hex_);
  }
  _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.common.v1.ReverseHex.hex)
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE ReverseHex::release_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* released = _impl_.hex_;
  _impl_.hex_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE ReverseHex::unsafe_arena_release_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.common.v1.ReverseHex.hex)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* temp = _impl_.hex_;
  _impl_.hex_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL ReverseHex::_internal_mutable_hex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hex_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::StringValue>(GetArena());
    _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(p);
  }
  return _impl_.hex_;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL ReverseHex::mutable_hex()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::StringValue* _msg = _internal_mutable_hex();
  // @@protoc_insertion_point(field_mutable:cusf.common.v1.ReverseHex.hex)
  return _msg;
}
inline void ReverseHex::set_allocated_hex(::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hex_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.hex_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.common.v1.ReverseHex.hex)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace common
}  // namespace cusf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cusf_2fcommon_2fv1_2fcommon_2eproto_2epb_2eh
