// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cusf/mainchain/v1/common.proto
// Protobuf C++ Version: 6.30.1

#include "cusf/mainchain/v1/common.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cusf {
namespace mainchain {
namespace v1 {

inline constexpr SidechainDeclaration_V0::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        title_{nullptr},
        description_{nullptr},
        hash_id_1_{nullptr},
        hash_id_2_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR SidechainDeclaration_V0::SidechainDeclaration_V0(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SidechainDeclaration_V0_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SidechainDeclaration_V0DefaultTypeInternal {
  PROTOBUF_CONSTEXPR SidechainDeclaration_V0DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SidechainDeclaration_V0DefaultTypeInternal() {}
  union {
    SidechainDeclaration_V0 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SidechainDeclaration_V0DefaultTypeInternal _SidechainDeclaration_V0_default_instance_;

inline constexpr OutPoint::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        txid_{nullptr},
        vout_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR OutPoint::OutPoint(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(OutPoint_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OutPointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OutPointDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OutPointDefaultTypeInternal() {}
  union {
    OutPoint _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OutPointDefaultTypeInternal _OutPoint_default_instance_;

inline constexpr SidechainDeclaration::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sidechain_declaration_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR SidechainDeclaration::SidechainDeclaration(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SidechainDeclaration_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SidechainDeclarationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SidechainDeclarationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SidechainDeclarationDefaultTypeInternal() {}
  union {
    SidechainDeclaration _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SidechainDeclarationDefaultTypeInternal _SidechainDeclaration_default_instance_;
}  // namespace v1
}  // namespace mainchain
}  // namespace cusf
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_cusf_2fmainchain_2fv1_2fcommon_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_cusf_2fmainchain_2fv1_2fcommon_2eproto = nullptr;
const ::uint32_t
    TableStruct_cusf_2fmainchain_2fv1_2fcommon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::OutPoint, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::OutPoint, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::OutPoint, _impl_.txid_),
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::OutPoint, _impl_.vout_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration_V0, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration_V0, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration_V0, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration_V0, _impl_.description_),
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration_V0, _impl_.hash_id_1_),
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration_V0, _impl_.hash_id_2_),
        0,
        1,
        2,
        3,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration, _impl_.sidechain_declaration_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::cusf::mainchain::v1::OutPoint)},
        {12, 24, -1, sizeof(::cusf::mainchain::v1::SidechainDeclaration_V0)},
        {28, -1, -1, sizeof(::cusf::mainchain::v1::SidechainDeclaration)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::cusf::mainchain::v1::_OutPoint_default_instance_._instance,
    &::cusf::mainchain::v1::_SidechainDeclaration_V0_default_instance_._instance,
    &::cusf::mainchain::v1::_SidechainDeclaration_default_instance_._instance,
};
const char descriptor_table_protodef_cusf_2fmainchain_2fv1_2fcommon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\036cusf/mainchain/v1/common.proto\022\021cusf.m"
    "ainchain.v1\032\036google/protobuf/wrappers.pr"
    "oto\032\033cusf/common/v1/common.proto\"l\n\010OutP"
    "oint\022.\n\004txid\030\001 \001(\0132\032.cusf.common.v1.Reve"
    "rseHexR\004txid\0220\n\004vout\030\002 \001(\0132\034.google.prot"
    "obuf.UInt32ValueR\004vout\"\323\002\n\024SidechainDecl"
    "aration\022<\n\002v0\030\001 \001(\0132*.cusf.mainchain.v1."
    "SidechainDeclaration.V0H\000R\002v0\032\343\001\n\002V0\0222\n\005"
    "title\030\001 \001(\0132\034.google.protobuf.StringValu"
    "eR\005title\022>\n\013description\030\002 \001(\0132\034.google.p"
    "rotobuf.StringValueR\013description\0228\n\thash"
    "_id_1\030\003 \001(\0132\034.cusf.common.v1.ConsensusHe"
    "xR\007hashId1\022/\n\thash_id_2\030\004 \001(\0132\023.cusf.com"
    "mon.v1.HexR\007hashId2B\027\n\025sidechain_declara"
    "tionB\212\001\n\025com.cusf.mainchain.v1B\013CommonPr"
    "otoP\001\242\002\003CMX\252\002\021Cusf.Mainchain.V1\312\002\021Cusf\\M"
    "ainchain\\V1\342\002\035Cusf\\Mainchain\\V1\\GPBMetad"
    "ata\352\002\023Cusf::Mainchain::V1b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto_deps[2] = {
        &::descriptor_table_cusf_2fcommon_2fv1_2fcommon_2eproto,
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::absl::once_flag descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto = {
    false,
    false,
    713,
    descriptor_table_protodef_cusf_2fmainchain_2fv1_2fcommon_2eproto,
    "cusf/mainchain/v1/common.proto",
    &descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto_once,
    descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_cusf_2fmainchain_2fv1_2fcommon_2eproto::offsets,
    file_level_enum_descriptors_cusf_2fmainchain_2fv1_2fcommon_2eproto,
    file_level_service_descriptors_cusf_2fmainchain_2fv1_2fcommon_2eproto,
};
namespace cusf {
namespace mainchain {
namespace v1 {
// ===================================================================

class OutPoint::_Internal {
 public:
  using HasBits =
      decltype(std::declval<OutPoint>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(OutPoint, _impl_._has_bits_);
};

void OutPoint::clear_txid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.txid_ != nullptr) _impl_.txid_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void OutPoint::clear_vout() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vout_ != nullptr) _impl_.vout_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
OutPoint::OutPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OutPoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cusf.mainchain.v1.OutPoint)
}
PROTOBUF_NDEBUG_INLINE OutPoint::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cusf::mainchain::v1::OutPoint& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

OutPoint::OutPoint(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const OutPoint& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, OutPoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OutPoint* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.txid_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.txid_)
                : nullptr;
  _impl_.vout_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.vout_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:cusf.mainchain.v1.OutPoint)
}
PROTOBUF_NDEBUG_INLINE OutPoint::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void OutPoint::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, txid_),
           0,
           offsetof(Impl_, vout_) -
               offsetof(Impl_, txid_) +
               sizeof(Impl_::vout_));
}
OutPoint::~OutPoint() {
  // @@protoc_insertion_point(destructor:cusf.mainchain.v1.OutPoint)
  SharedDtor(*this);
}
inline void OutPoint::SharedDtor(MessageLite& self) {
  OutPoint& this_ = static_cast<OutPoint&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.txid_;
  delete this_._impl_.vout_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL OutPoint::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) OutPoint(arena);
}
constexpr auto OutPoint::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(OutPoint),
                                            alignof(OutPoint));
}
constexpr auto OutPoint::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_OutPoint_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &OutPoint::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<OutPoint>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &OutPoint::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<OutPoint>(), &OutPoint::ByteSizeLong,
              &OutPoint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(OutPoint, _impl_._cached_size_),
          false,
      },
      &OutPoint::kDescriptorMethods,
      &descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        OutPoint_class_data_ =
            OutPoint::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL OutPoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&OutPoint_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(OutPoint_class_data_.tc_table);
  return OutPoint_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
OutPoint::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(OutPoint, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    OutPoint_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cusf::mainchain::v1::OutPoint>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .google.protobuf.UInt32Value vout = 2 [json_name = "vout"];
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(OutPoint, _impl_.vout_)}},
    // .cusf.common.v1.ReverseHex txid = 1 [json_name = "txid"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(OutPoint, _impl_.txid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .cusf.common.v1.ReverseHex txid = 1 [json_name = "txid"];
    {PROTOBUF_FIELD_OFFSET(OutPoint, _impl_.txid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.UInt32Value vout = 2 [json_name = "vout"];
    {PROTOBUF_FIELD_OFFSET(OutPoint, _impl_.vout_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cusf::common::v1::ReverseHex>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::UInt32Value>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void OutPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:cusf.mainchain.v1.OutPoint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(_impl_.txid_ != nullptr);
      _impl_.txid_->Clear();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.vout_ != nullptr);
      _impl_.vout_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL OutPoint::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const OutPoint& this_ = static_cast<const OutPoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL OutPoint::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const OutPoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cusf.mainchain.v1.OutPoint)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .cusf.common.v1.ReverseHex txid = 1 [json_name = "txid"];
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.txid_, this_._impl_.txid_->GetCachedSize(), target,
        stream);
  }

  // .google.protobuf.UInt32Value vout = 2 [json_name = "vout"];
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.vout_, this_._impl_.vout_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cusf.mainchain.v1.OutPoint)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t OutPoint::ByteSizeLong(const MessageLite& base) {
  const OutPoint& this_ = static_cast<const OutPoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t OutPoint::ByteSizeLong() const {
  const OutPoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cusf.mainchain.v1.OutPoint)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // .cusf.common.v1.ReverseHex txid = 1 [json_name = "txid"];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.txid_);
    }
    // .google.protobuf.UInt32Value vout = 2 [json_name = "vout"];
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.vout_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void OutPoint::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OutPoint*>(&to_msg);
  auto& from = static_cast<const OutPoint&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cusf.mainchain.v1.OutPoint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.txid_ != nullptr);
      if (_this->_impl_.txid_ == nullptr) {
        _this->_impl_.txid_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.txid_);
      } else {
        _this->_impl_.txid_->MergeFrom(*from._impl_.txid_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.vout_ != nullptr);
      if (_this->_impl_.vout_ == nullptr) {
        _this->_impl_.vout_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.vout_);
      } else {
        _this->_impl_.vout_->MergeFrom(*from._impl_.vout_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OutPoint::CopyFrom(const OutPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cusf.mainchain.v1.OutPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OutPoint::InternalSwap(OutPoint* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OutPoint, _impl_.vout_)
      + sizeof(OutPoint::_impl_.vout_)
      - PROTOBUF_FIELD_OFFSET(OutPoint, _impl_.txid_)>(
          reinterpret_cast<char*>(&_impl_.txid_),
          reinterpret_cast<char*>(&other->_impl_.txid_));
}

::google::protobuf::Metadata OutPoint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SidechainDeclaration_V0::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SidechainDeclaration_V0>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_._has_bits_);
};

void SidechainDeclaration_V0::clear_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.title_ != nullptr) _impl_.title_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void SidechainDeclaration_V0::clear_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.description_ != nullptr) _impl_.description_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void SidechainDeclaration_V0::clear_hash_id_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hash_id_1_ != nullptr) _impl_.hash_id_1_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void SidechainDeclaration_V0::clear_hash_id_2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hash_id_2_ != nullptr) _impl_.hash_id_2_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
SidechainDeclaration_V0::SidechainDeclaration_V0(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidechainDeclaration_V0_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cusf.mainchain.v1.SidechainDeclaration.V0)
}
PROTOBUF_NDEBUG_INLINE SidechainDeclaration_V0::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cusf::mainchain::v1::SidechainDeclaration_V0& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SidechainDeclaration_V0::SidechainDeclaration_V0(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SidechainDeclaration_V0& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidechainDeclaration_V0_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SidechainDeclaration_V0* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.title_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.title_)
                : nullptr;
  _impl_.description_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.description_)
                : nullptr;
  _impl_.hash_id_1_ = ((cached_has_bits & 0x00000004u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.hash_id_1_)
                : nullptr;
  _impl_.hash_id_2_ = ((cached_has_bits & 0x00000008u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.hash_id_2_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:cusf.mainchain.v1.SidechainDeclaration.V0)
}
PROTOBUF_NDEBUG_INLINE SidechainDeclaration_V0::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SidechainDeclaration_V0::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, title_),
           0,
           offsetof(Impl_, hash_id_2_) -
               offsetof(Impl_, title_) +
               sizeof(Impl_::hash_id_2_));
}
SidechainDeclaration_V0::~SidechainDeclaration_V0() {
  // @@protoc_insertion_point(destructor:cusf.mainchain.v1.SidechainDeclaration.V0)
  SharedDtor(*this);
}
inline void SidechainDeclaration_V0::SharedDtor(MessageLite& self) {
  SidechainDeclaration_V0& this_ = static_cast<SidechainDeclaration_V0&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.title_;
  delete this_._impl_.description_;
  delete this_._impl_.hash_id_1_;
  delete this_._impl_.hash_id_2_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SidechainDeclaration_V0::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SidechainDeclaration_V0(arena);
}
constexpr auto SidechainDeclaration_V0::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SidechainDeclaration_V0),
                                            alignof(SidechainDeclaration_V0));
}
constexpr auto SidechainDeclaration_V0::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SidechainDeclaration_V0_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SidechainDeclaration_V0::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SidechainDeclaration_V0>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SidechainDeclaration_V0::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SidechainDeclaration_V0>(), &SidechainDeclaration_V0::ByteSizeLong,
              &SidechainDeclaration_V0::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_._cached_size_),
          false,
      },
      &SidechainDeclaration_V0::kDescriptorMethods,
      &descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        SidechainDeclaration_V0_class_data_ =
            SidechainDeclaration_V0::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SidechainDeclaration_V0::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SidechainDeclaration_V0_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SidechainDeclaration_V0_class_data_.tc_table);
  return SidechainDeclaration_V0_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 4, 0, 2>
SidechainDeclaration_V0::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SidechainDeclaration_V0_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cusf::mainchain::v1::SidechainDeclaration_V0>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .cusf.common.v1.Hex hash_id_2 = 4 [json_name = "hashId2"];
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3, PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.hash_id_2_)}},
    // .google.protobuf.StringValue title = 1 [json_name = "title"];
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.title_)}},
    // .google.protobuf.StringValue description = 2 [json_name = "description"];
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.description_)}},
    // .cusf.common.v1.ConsensusHex hash_id_1 = 3 [json_name = "hashId1"];
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.hash_id_1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .google.protobuf.StringValue title = 1 [json_name = "title"];
    {PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.title_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.StringValue description = 2 [json_name = "description"];
    {PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.description_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .cusf.common.v1.ConsensusHex hash_id_1 = 3 [json_name = "hashId1"];
    {PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.hash_id_1_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .cusf.common.v1.Hex hash_id_2 = 4 [json_name = "hashId2"];
    {PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.hash_id_2_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::google::protobuf::StringValue>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::StringValue>()},
      {::_pbi::TcParser::GetTable<::cusf::common::v1::ConsensusHex>()},
      {::_pbi::TcParser::GetTable<::cusf::common::v1::Hex>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SidechainDeclaration_V0::Clear() {
// @@protoc_insertion_point(message_clear_start:cusf.mainchain.v1.SidechainDeclaration.V0)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(_impl_.title_ != nullptr);
      _impl_.title_->Clear();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.description_ != nullptr);
      _impl_.description_->Clear();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(_impl_.hash_id_1_ != nullptr);
      _impl_.hash_id_1_->Clear();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(_impl_.hash_id_2_ != nullptr);
      _impl_.hash_id_2_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SidechainDeclaration_V0::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SidechainDeclaration_V0& this_ = static_cast<const SidechainDeclaration_V0&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SidechainDeclaration_V0::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SidechainDeclaration_V0& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cusf.mainchain.v1.SidechainDeclaration.V0)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .google.protobuf.StringValue title = 1 [json_name = "title"];
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.title_, this_._impl_.title_->GetCachedSize(), target,
        stream);
  }

  // .google.protobuf.StringValue description = 2 [json_name = "description"];
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.description_, this_._impl_.description_->GetCachedSize(), target,
        stream);
  }

  // .cusf.common.v1.ConsensusHex hash_id_1 = 3 [json_name = "hashId1"];
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.hash_id_1_, this_._impl_.hash_id_1_->GetCachedSize(), target,
        stream);
  }

  // .cusf.common.v1.Hex hash_id_2 = 4 [json_name = "hashId2"];
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.hash_id_2_, this_._impl_.hash_id_2_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cusf.mainchain.v1.SidechainDeclaration.V0)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SidechainDeclaration_V0::ByteSizeLong(const MessageLite& base) {
  const SidechainDeclaration_V0& this_ = static_cast<const SidechainDeclaration_V0&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SidechainDeclaration_V0::ByteSizeLong() const {
  const SidechainDeclaration_V0& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cusf.mainchain.v1.SidechainDeclaration.V0)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    // .google.protobuf.StringValue title = 1 [json_name = "title"];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.title_);
    }
    // .google.protobuf.StringValue description = 2 [json_name = "description"];
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.description_);
    }
    // .cusf.common.v1.ConsensusHex hash_id_1 = 3 [json_name = "hashId1"];
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.hash_id_1_);
    }
    // .cusf.common.v1.Hex hash_id_2 = 4 [json_name = "hashId2"];
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.hash_id_2_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SidechainDeclaration_V0::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SidechainDeclaration_V0*>(&to_msg);
  auto& from = static_cast<const SidechainDeclaration_V0&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cusf.mainchain.v1.SidechainDeclaration.V0)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.title_ != nullptr);
      if (_this->_impl_.title_ == nullptr) {
        _this->_impl_.title_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.title_);
      } else {
        _this->_impl_.title_->MergeFrom(*from._impl_.title_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.description_ != nullptr);
      if (_this->_impl_.description_ == nullptr) {
        _this->_impl_.description_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.description_);
      } else {
        _this->_impl_.description_->MergeFrom(*from._impl_.description_);
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(from._impl_.hash_id_1_ != nullptr);
      if (_this->_impl_.hash_id_1_ == nullptr) {
        _this->_impl_.hash_id_1_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.hash_id_1_);
      } else {
        _this->_impl_.hash_id_1_->MergeFrom(*from._impl_.hash_id_1_);
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(from._impl_.hash_id_2_ != nullptr);
      if (_this->_impl_.hash_id_2_ == nullptr) {
        _this->_impl_.hash_id_2_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.hash_id_2_);
      } else {
        _this->_impl_.hash_id_2_->MergeFrom(*from._impl_.hash_id_2_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SidechainDeclaration_V0::CopyFrom(const SidechainDeclaration_V0& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cusf.mainchain.v1.SidechainDeclaration.V0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SidechainDeclaration_V0::InternalSwap(SidechainDeclaration_V0* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.hash_id_2_)
      + sizeof(SidechainDeclaration_V0::_impl_.hash_id_2_)
      - PROTOBUF_FIELD_OFFSET(SidechainDeclaration_V0, _impl_.title_)>(
          reinterpret_cast<char*>(&_impl_.title_),
          reinterpret_cast<char*>(&other->_impl_.title_));
}

::google::protobuf::Metadata SidechainDeclaration_V0::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SidechainDeclaration::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::cusf::mainchain::v1::SidechainDeclaration, _impl_._oneof_case_);
};

void SidechainDeclaration::set_allocated_v0(::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE v0) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_sidechain_declaration();
  if (v0) {
    ::google::protobuf::Arena* submessage_arena = v0->GetArena();
    if (message_arena != submessage_arena) {
      v0 = ::google::protobuf::internal::GetOwnedMessage(message_arena, v0, submessage_arena);
    }
    set_has_v0();
    _impl_.sidechain_declaration_.v0_ = v0;
  }
  // @@protoc_insertion_point(field_set_allocated:cusf.mainchain.v1.SidechainDeclaration.v0)
}
SidechainDeclaration::SidechainDeclaration(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidechainDeclaration_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cusf.mainchain.v1.SidechainDeclaration)
}
PROTOBUF_NDEBUG_INLINE SidechainDeclaration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cusf::mainchain::v1::SidechainDeclaration& from_msg)
      : sidechain_declaration_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

SidechainDeclaration::SidechainDeclaration(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SidechainDeclaration& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidechainDeclaration_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SidechainDeclaration* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (sidechain_declaration_case()) {
    case SIDECHAIN_DECLARATION_NOT_SET:
      break;
      case kV0:
        _impl_.sidechain_declaration_.v0_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sidechain_declaration_.v0_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:cusf.mainchain.v1.SidechainDeclaration)
}
PROTOBUF_NDEBUG_INLINE SidechainDeclaration::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : sidechain_declaration_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void SidechainDeclaration::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SidechainDeclaration::~SidechainDeclaration() {
  // @@protoc_insertion_point(destructor:cusf.mainchain.v1.SidechainDeclaration)
  SharedDtor(*this);
}
inline void SidechainDeclaration::SharedDtor(MessageLite& self) {
  SidechainDeclaration& this_ = static_cast<SidechainDeclaration&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_sidechain_declaration()) {
    this_.clear_sidechain_declaration();
  }
  this_._impl_.~Impl_();
}

void SidechainDeclaration::clear_sidechain_declaration() {
// @@protoc_insertion_point(one_of_clear_start:cusf.mainchain.v1.SidechainDeclaration)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (sidechain_declaration_case()) {
    case kV0: {
      if (GetArena() == nullptr) {
        delete _impl_.sidechain_declaration_.v0_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.sidechain_declaration_.v0_);
      }
      break;
    }
    case SIDECHAIN_DECLARATION_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SIDECHAIN_DECLARATION_NOT_SET;
}


inline void* PROTOBUF_NONNULL SidechainDeclaration::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SidechainDeclaration(arena);
}
constexpr auto SidechainDeclaration::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SidechainDeclaration),
                                            alignof(SidechainDeclaration));
}
constexpr auto SidechainDeclaration::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SidechainDeclaration_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SidechainDeclaration::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SidechainDeclaration>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SidechainDeclaration::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SidechainDeclaration>(), &SidechainDeclaration::ByteSizeLong,
              &SidechainDeclaration::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SidechainDeclaration, _impl_._cached_size_),
          false,
      },
      &SidechainDeclaration::kDescriptorMethods,
      &descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        SidechainDeclaration_class_data_ =
            SidechainDeclaration::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SidechainDeclaration::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SidechainDeclaration_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SidechainDeclaration_class_data_.tc_table);
  return SidechainDeclaration_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
SidechainDeclaration::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SidechainDeclaration_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cusf::mainchain::v1::SidechainDeclaration>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .cusf.mainchain.v1.SidechainDeclaration.V0 v0 = 1 [json_name = "v0"];
    {PROTOBUF_FIELD_OFFSET(SidechainDeclaration, _impl_.sidechain_declaration_.v0_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cusf::mainchain::v1::SidechainDeclaration_V0>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SidechainDeclaration::Clear() {
// @@protoc_insertion_point(message_clear_start:cusf.mainchain.v1.SidechainDeclaration)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_sidechain_declaration();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SidechainDeclaration::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SidechainDeclaration& this_ = static_cast<const SidechainDeclaration&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SidechainDeclaration::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SidechainDeclaration& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cusf.mainchain.v1.SidechainDeclaration)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .cusf.mainchain.v1.SidechainDeclaration.V0 v0 = 1 [json_name = "v0"];
  if (this_.sidechain_declaration_case() == kV0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.sidechain_declaration_.v0_, this_._impl_.sidechain_declaration_.v0_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cusf.mainchain.v1.SidechainDeclaration)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SidechainDeclaration::ByteSizeLong(const MessageLite& base) {
  const SidechainDeclaration& this_ = static_cast<const SidechainDeclaration&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SidechainDeclaration::ByteSizeLong() const {
  const SidechainDeclaration& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cusf.mainchain.v1.SidechainDeclaration)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.sidechain_declaration_case()) {
    // .cusf.mainchain.v1.SidechainDeclaration.V0 v0 = 1 [json_name = "v0"];
    case kV0: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.sidechain_declaration_.v0_);
      break;
    }
    case SIDECHAIN_DECLARATION_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SidechainDeclaration::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SidechainDeclaration*>(&to_msg);
  auto& from = static_cast<const SidechainDeclaration&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cusf.mainchain.v1.SidechainDeclaration)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_sidechain_declaration();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kV0: {
        if (oneof_needs_init) {
          _this->_impl_.sidechain_declaration_.v0_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sidechain_declaration_.v0_);
        } else {
          _this->_impl_.sidechain_declaration_.v0_->MergeFrom(*from._impl_.sidechain_declaration_.v0_);
        }
        break;
      }
      case SIDECHAIN_DECLARATION_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SidechainDeclaration::CopyFrom(const SidechainDeclaration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cusf.mainchain.v1.SidechainDeclaration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SidechainDeclaration::InternalSwap(SidechainDeclaration* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.sidechain_declaration_, other->_impl_.sidechain_declaration_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata SidechainDeclaration::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace mainchain
}  // namespace cusf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
