// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cusf/mainchain/v1/common.proto
// Protobuf C++ Version: 6.30.1

#ifndef cusf_2fmainchain_2fv1_2fcommon_2eproto_2epb_2eh
#define cusf_2fmainchain_2fv1_2fcommon_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/wrappers.pb.h"
#include "cusf/common/v1/common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cusf_2fmainchain_2fv1_2fcommon_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cusf_2fmainchain_2fv1_2fcommon_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cusf_2fmainchain_2fv1_2fcommon_2eproto;
}  // extern "C"
namespace cusf {
namespace mainchain {
namespace v1 {
class OutPoint;
struct OutPointDefaultTypeInternal;
extern OutPointDefaultTypeInternal _OutPoint_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull OutPoint_class_data_;
class SidechainDeclaration;
struct SidechainDeclarationDefaultTypeInternal;
extern SidechainDeclarationDefaultTypeInternal _SidechainDeclaration_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SidechainDeclaration_class_data_;
class SidechainDeclaration_V0;
struct SidechainDeclaration_V0DefaultTypeInternal;
extern SidechainDeclaration_V0DefaultTypeInternal _SidechainDeclaration_V0_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SidechainDeclaration_V0_class_data_;
}  // namespace v1
}  // namespace mainchain
}  // namespace cusf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cusf {
namespace mainchain {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class SidechainDeclaration_V0 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cusf.mainchain.v1.SidechainDeclaration.V0) */ {
 public:
  inline SidechainDeclaration_V0() : SidechainDeclaration_V0(nullptr) {}
  ~SidechainDeclaration_V0() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SidechainDeclaration_V0* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SidechainDeclaration_V0));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SidechainDeclaration_V0(::google::protobuf::internal::ConstantInitialized);

  inline SidechainDeclaration_V0(const SidechainDeclaration_V0& from) : SidechainDeclaration_V0(nullptr, from) {}
  inline SidechainDeclaration_V0(SidechainDeclaration_V0&& from) noexcept
      : SidechainDeclaration_V0(nullptr, std::move(from)) {}
  inline SidechainDeclaration_V0& operator=(const SidechainDeclaration_V0& from) {
    CopyFrom(from);
    return *this;
  }
  inline SidechainDeclaration_V0& operator=(SidechainDeclaration_V0&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SidechainDeclaration_V0& default_instance() {
    return *reinterpret_cast<const SidechainDeclaration_V0*>(
        &_SidechainDeclaration_V0_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SidechainDeclaration_V0& a, SidechainDeclaration_V0& b) { a.Swap(&b); }
  inline void Swap(SidechainDeclaration_V0* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SidechainDeclaration_V0* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SidechainDeclaration_V0* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SidechainDeclaration_V0>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SidechainDeclaration_V0& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SidechainDeclaration_V0& from) { SidechainDeclaration_V0::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SidechainDeclaration_V0* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cusf.mainchain.v1.SidechainDeclaration.V0"; }

 protected:
  explicit SidechainDeclaration_V0(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SidechainDeclaration_V0(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SidechainDeclaration_V0& from);
  SidechainDeclaration_V0(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SidechainDeclaration_V0&& from) noexcept
      : SidechainDeclaration_V0(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTitleFieldNumber = 1,
    kDescriptionFieldNumber = 2,
    kHashId1FieldNumber = 3,
    kHashId2FieldNumber = 4,
  };
  // .google.protobuf.StringValue title = 1 [json_name = "title"];
  bool has_title() const;
  void clear_title() ;
  const ::google::protobuf::StringValue& title() const;
  [[nodiscard]] ::google::protobuf::StringValue* PROTOBUF_NULLABLE release_title();
  ::google::protobuf::StringValue* PROTOBUF_NONNULL mutable_title();
  void set_allocated_title(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_title(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  ::google::protobuf::StringValue* PROTOBUF_NULLABLE unsafe_arena_release_title();

  private:
  const ::google::protobuf::StringValue& _internal_title() const;
  ::google::protobuf::StringValue* PROTOBUF_NONNULL _internal_mutable_title();

  public:
  // .google.protobuf.StringValue description = 2 [json_name = "description"];
  bool has_description() const;
  void clear_description() ;
  const ::google::protobuf::StringValue& description() const;
  [[nodiscard]] ::google::protobuf::StringValue* PROTOBUF_NULLABLE release_description();
  ::google::protobuf::StringValue* PROTOBUF_NONNULL mutable_description();
  void set_allocated_description(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_description(::google::protobuf::StringValue* PROTOBUF_NULLABLE value);
  ::google::protobuf::StringValue* PROTOBUF_NULLABLE unsafe_arena_release_description();

  private:
  const ::google::protobuf::StringValue& _internal_description() const;
  ::google::protobuf::StringValue* PROTOBUF_NONNULL _internal_mutable_description();

  public:
  // .cusf.common.v1.ConsensusHex hash_id_1 = 3 [json_name = "hashId1"];
  bool has_hash_id_1() const;
  void clear_hash_id_1() ;
  const ::cusf::common::v1::ConsensusHex& hash_id_1() const;
  [[nodiscard]] ::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE release_hash_id_1();
  ::cusf::common::v1::ConsensusHex* PROTOBUF_NONNULL mutable_hash_id_1();
  void set_allocated_hash_id_1(::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_hash_id_1(::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE value);
  ::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE unsafe_arena_release_hash_id_1();

  private:
  const ::cusf::common::v1::ConsensusHex& _internal_hash_id_1() const;
  ::cusf::common::v1::ConsensusHex* PROTOBUF_NONNULL _internal_mutable_hash_id_1();

  public:
  // .cusf.common.v1.Hex hash_id_2 = 4 [json_name = "hashId2"];
  bool has_hash_id_2() const;
  void clear_hash_id_2() ;
  const ::cusf::common::v1::Hex& hash_id_2() const;
  [[nodiscard]] ::cusf::common::v1::Hex* PROTOBUF_NULLABLE release_hash_id_2();
  ::cusf::common::v1::Hex* PROTOBUF_NONNULL mutable_hash_id_2();
  void set_allocated_hash_id_2(::cusf::common::v1::Hex* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_hash_id_2(::cusf::common::v1::Hex* PROTOBUF_NULLABLE value);
  ::cusf::common::v1::Hex* PROTOBUF_NULLABLE unsafe_arena_release_hash_id_2();

  private:
  const ::cusf::common::v1::Hex& _internal_hash_id_2() const;
  ::cusf::common::v1::Hex* PROTOBUF_NONNULL _internal_mutable_hash_id_2();

  public:
  // @@protoc_insertion_point(class_scope:cusf.mainchain.v1.SidechainDeclaration.V0)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   4, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SidechainDeclaration_V0& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE title_;
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE description_;
    ::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE hash_id_1_;
    ::cusf::common::v1::Hex* PROTOBUF_NULLABLE hash_id_2_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cusf_2fmainchain_2fv1_2fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SidechainDeclaration_V0_class_data_;
// -------------------------------------------------------------------

class OutPoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cusf.mainchain.v1.OutPoint) */ {
 public:
  inline OutPoint() : OutPoint(nullptr) {}
  ~OutPoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OutPoint* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OutPoint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OutPoint(::google::protobuf::internal::ConstantInitialized);

  inline OutPoint(const OutPoint& from) : OutPoint(nullptr, from) {}
  inline OutPoint(OutPoint&& from) noexcept
      : OutPoint(nullptr, std::move(from)) {}
  inline OutPoint& operator=(const OutPoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline OutPoint& operator=(OutPoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OutPoint& default_instance() {
    return *reinterpret_cast<const OutPoint*>(
        &_OutPoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(OutPoint& a, OutPoint& b) { a.Swap(&b); }
  inline void Swap(OutPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OutPoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OutPoint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OutPoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OutPoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OutPoint& from) { OutPoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OutPoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cusf.mainchain.v1.OutPoint"; }

 protected:
  explicit OutPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  OutPoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const OutPoint& from);
  OutPoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, OutPoint&& from) noexcept
      : OutPoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTxidFieldNumber = 1,
    kVoutFieldNumber = 2,
  };
  // .cusf.common.v1.ReverseHex txid = 1 [json_name = "txid"];
  bool has_txid() const;
  void clear_txid() ;
  const ::cusf::common::v1::ReverseHex& txid() const;
  [[nodiscard]] ::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE release_txid();
  ::cusf::common::v1::ReverseHex* PROTOBUF_NONNULL mutable_txid();
  void set_allocated_txid(::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_txid(::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE value);
  ::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE unsafe_arena_release_txid();

  private:
  const ::cusf::common::v1::ReverseHex& _internal_txid() const;
  ::cusf::common::v1::ReverseHex* PROTOBUF_NONNULL _internal_mutable_txid();

  public:
  // .google.protobuf.UInt32Value vout = 2 [json_name = "vout"];
  bool has_vout() const;
  void clear_vout() ;
  const ::google::protobuf::UInt32Value& vout() const;
  [[nodiscard]] ::google::protobuf::UInt32Value* PROTOBUF_NULLABLE release_vout();
  ::google::protobuf::UInt32Value* PROTOBUF_NONNULL mutable_vout();
  void set_allocated_vout(::google::protobuf::UInt32Value* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_vout(::google::protobuf::UInt32Value* PROTOBUF_NULLABLE value);
  ::google::protobuf::UInt32Value* PROTOBUF_NULLABLE unsafe_arena_release_vout();

  private:
  const ::google::protobuf::UInt32Value& _internal_vout() const;
  ::google::protobuf::UInt32Value* PROTOBUF_NONNULL _internal_mutable_vout();

  public:
  // @@protoc_insertion_point(class_scope:cusf.mainchain.v1.OutPoint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const OutPoint& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE txid_;
    ::google::protobuf::UInt32Value* PROTOBUF_NULLABLE vout_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cusf_2fmainchain_2fv1_2fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull OutPoint_class_data_;
// -------------------------------------------------------------------

class SidechainDeclaration final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cusf.mainchain.v1.SidechainDeclaration) */ {
 public:
  inline SidechainDeclaration() : SidechainDeclaration(nullptr) {}
  ~SidechainDeclaration() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SidechainDeclaration* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SidechainDeclaration));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SidechainDeclaration(::google::protobuf::internal::ConstantInitialized);

  inline SidechainDeclaration(const SidechainDeclaration& from) : SidechainDeclaration(nullptr, from) {}
  inline SidechainDeclaration(SidechainDeclaration&& from) noexcept
      : SidechainDeclaration(nullptr, std::move(from)) {}
  inline SidechainDeclaration& operator=(const SidechainDeclaration& from) {
    CopyFrom(from);
    return *this;
  }
  inline SidechainDeclaration& operator=(SidechainDeclaration&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SidechainDeclaration& default_instance() {
    return *reinterpret_cast<const SidechainDeclaration*>(
        &_SidechainDeclaration_default_instance_);
  }
  enum SidechainDeclarationCase {
    kV0 = 1,
    SIDECHAIN_DECLARATION_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SidechainDeclaration& a, SidechainDeclaration& b) { a.Swap(&b); }
  inline void Swap(SidechainDeclaration* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SidechainDeclaration* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SidechainDeclaration* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SidechainDeclaration>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SidechainDeclaration& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SidechainDeclaration& from) { SidechainDeclaration::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SidechainDeclaration* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cusf.mainchain.v1.SidechainDeclaration"; }

 protected:
  explicit SidechainDeclaration(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SidechainDeclaration(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SidechainDeclaration& from);
  SidechainDeclaration(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SidechainDeclaration&& from) noexcept
      : SidechainDeclaration(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using V0 = SidechainDeclaration_V0;

  // accessors -------------------------------------------------------
  enum : int {
    kV0FieldNumber = 1,
  };
  // .cusf.mainchain.v1.SidechainDeclaration.V0 v0 = 1 [json_name = "v0"];
  bool has_v0() const;
  private:
  bool _internal_has_v0() const;

  public:
  void clear_v0() ;
  const ::cusf::mainchain::v1::SidechainDeclaration_V0& v0() const;
  [[nodiscard]] ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE release_v0();
  ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NONNULL mutable_v0();
  void set_allocated_v0(::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_v0(::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE value);
  ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE unsafe_arena_release_v0();

  private:
  const ::cusf::mainchain::v1::SidechainDeclaration_V0& _internal_v0() const;
  ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NONNULL _internal_mutable_v0();

  public:
  void clear_sidechain_declaration();
  SidechainDeclarationCase sidechain_declaration_case() const;
  // @@protoc_insertion_point(class_scope:cusf.mainchain.v1.SidechainDeclaration)
 private:
  class _Internal;
  void set_has_v0();
  inline bool has_sidechain_declaration() const;
  inline void clear_has_sidechain_declaration();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SidechainDeclaration& from_msg);
    union SidechainDeclarationUnion {
      constexpr SidechainDeclarationUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE v0_;
    } sidechain_declaration_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cusf_2fmainchain_2fv1_2fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SidechainDeclaration_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OutPoint

// .cusf.common.v1.ReverseHex txid = 1 [json_name = "txid"];
inline bool OutPoint::has_txid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.txid_ != nullptr);
  return value;
}
inline const ::cusf::common::v1::ReverseHex& OutPoint::_internal_txid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::cusf::common::v1::ReverseHex* p = _impl_.txid_;
  return p != nullptr ? *p : reinterpret_cast<const ::cusf::common::v1::ReverseHex&>(::cusf::common::v1::_ReverseHex_default_instance_);
}
inline const ::cusf::common::v1::ReverseHex& OutPoint::txid() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.mainchain.v1.OutPoint.txid)
  return _internal_txid();
}
inline void OutPoint::unsafe_arena_set_allocated_txid(
    ::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.txid_);
  }
  _impl_.txid_ = reinterpret_cast<::cusf::common::v1::ReverseHex*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.mainchain.v1.OutPoint.txid)
}
inline ::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE OutPoint::release_txid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::cusf::common::v1::ReverseHex* released = _impl_.txid_;
  _impl_.txid_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE OutPoint::unsafe_arena_release_txid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.mainchain.v1.OutPoint.txid)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::cusf::common::v1::ReverseHex* temp = _impl_.txid_;
  _impl_.txid_ = nullptr;
  return temp;
}
inline ::cusf::common::v1::ReverseHex* PROTOBUF_NONNULL OutPoint::_internal_mutable_txid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.txid_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::cusf::common::v1::ReverseHex>(GetArena());
    _impl_.txid_ = reinterpret_cast<::cusf::common::v1::ReverseHex*>(p);
  }
  return _impl_.txid_;
}
inline ::cusf::common::v1::ReverseHex* PROTOBUF_NONNULL OutPoint::mutable_txid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::cusf::common::v1::ReverseHex* _msg = _internal_mutable_txid();
  // @@protoc_insertion_point(field_mutable:cusf.mainchain.v1.OutPoint.txid)
  return _msg;
}
inline void OutPoint::set_allocated_txid(::cusf::common::v1::ReverseHex* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.txid_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.txid_ = reinterpret_cast<::cusf::common::v1::ReverseHex*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.mainchain.v1.OutPoint.txid)
}

// .google.protobuf.UInt32Value vout = 2 [json_name = "vout"];
inline bool OutPoint::has_vout() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.vout_ != nullptr);
  return value;
}
inline const ::google::protobuf::UInt32Value& OutPoint::_internal_vout() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::UInt32Value* p = _impl_.vout_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::UInt32Value&>(::google::protobuf::_UInt32Value_default_instance_);
}
inline const ::google::protobuf::UInt32Value& OutPoint::vout() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.mainchain.v1.OutPoint.vout)
  return _internal_vout();
}
inline void OutPoint::unsafe_arena_set_allocated_vout(
    ::google::protobuf::UInt32Value* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vout_);
  }
  _impl_.vout_ = reinterpret_cast<::google::protobuf::UInt32Value*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.mainchain.v1.OutPoint.vout)
}
inline ::google::protobuf::UInt32Value* PROTOBUF_NULLABLE OutPoint::release_vout() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::UInt32Value* released = _impl_.vout_;
  _impl_.vout_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::UInt32Value* PROTOBUF_NULLABLE OutPoint::unsafe_arena_release_vout() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.mainchain.v1.OutPoint.vout)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::UInt32Value* temp = _impl_.vout_;
  _impl_.vout_ = nullptr;
  return temp;
}
inline ::google::protobuf::UInt32Value* PROTOBUF_NONNULL OutPoint::_internal_mutable_vout() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.vout_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::UInt32Value>(GetArena());
    _impl_.vout_ = reinterpret_cast<::google::protobuf::UInt32Value*>(p);
  }
  return _impl_.vout_;
}
inline ::google::protobuf::UInt32Value* PROTOBUF_NONNULL OutPoint::mutable_vout()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::google::protobuf::UInt32Value* _msg = _internal_mutable_vout();
  // @@protoc_insertion_point(field_mutable:cusf.mainchain.v1.OutPoint.vout)
  return _msg;
}
inline void OutPoint::set_allocated_vout(::google::protobuf::UInt32Value* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.vout_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.vout_ = reinterpret_cast<::google::protobuf::UInt32Value*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.mainchain.v1.OutPoint.vout)
}

// -------------------------------------------------------------------

// SidechainDeclaration_V0

// .google.protobuf.StringValue title = 1 [json_name = "title"];
inline bool SidechainDeclaration_V0::has_title() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.title_ != nullptr);
  return value;
}
inline const ::google::protobuf::StringValue& SidechainDeclaration_V0::_internal_title() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::StringValue* p = _impl_.title_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::StringValue&>(::google::protobuf::_StringValue_default_instance_);
}
inline const ::google::protobuf::StringValue& SidechainDeclaration_V0::title() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.mainchain.v1.SidechainDeclaration.V0.title)
  return _internal_title();
}
inline void SidechainDeclaration_V0::unsafe_arena_set_allocated_title(
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.title_);
  }
  _impl_.title_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.title)
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE SidechainDeclaration_V0::release_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* released = _impl_.title_;
  _impl_.title_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE SidechainDeclaration_V0::unsafe_arena_release_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.mainchain.v1.SidechainDeclaration.V0.title)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::google::protobuf::StringValue* temp = _impl_.title_;
  _impl_.title_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL SidechainDeclaration_V0::_internal_mutable_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.title_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::StringValue>(GetArena());
    _impl_.title_ = reinterpret_cast<::google::protobuf::StringValue*>(p);
  }
  return _impl_.title_;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL SidechainDeclaration_V0::mutable_title()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::google::protobuf::StringValue* _msg = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:cusf.mainchain.v1.SidechainDeclaration.V0.title)
  return _msg;
}
inline void SidechainDeclaration_V0::set_allocated_title(::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.title_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.title_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.title)
}

// .google.protobuf.StringValue description = 2 [json_name = "description"];
inline bool SidechainDeclaration_V0::has_description() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.description_ != nullptr);
  return value;
}
inline const ::google::protobuf::StringValue& SidechainDeclaration_V0::_internal_description() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::StringValue* p = _impl_.description_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::StringValue&>(::google::protobuf::_StringValue_default_instance_);
}
inline const ::google::protobuf::StringValue& SidechainDeclaration_V0::description() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.mainchain.v1.SidechainDeclaration.V0.description)
  return _internal_description();
}
inline void SidechainDeclaration_V0::unsafe_arena_set_allocated_description(
    ::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.description_);
  }
  _impl_.description_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.description)
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE SidechainDeclaration_V0::release_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::StringValue* released = _impl_.description_;
  _impl_.description_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::StringValue* PROTOBUF_NULLABLE SidechainDeclaration_V0::unsafe_arena_release_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.mainchain.v1.SidechainDeclaration.V0.description)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::google::protobuf::StringValue* temp = _impl_.description_;
  _impl_.description_ = nullptr;
  return temp;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL SidechainDeclaration_V0::_internal_mutable_description() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.description_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::StringValue>(GetArena());
    _impl_.description_ = reinterpret_cast<::google::protobuf::StringValue*>(p);
  }
  return _impl_.description_;
}
inline ::google::protobuf::StringValue* PROTOBUF_NONNULL SidechainDeclaration_V0::mutable_description()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::google::protobuf::StringValue* _msg = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:cusf.mainchain.v1.SidechainDeclaration.V0.description)
  return _msg;
}
inline void SidechainDeclaration_V0::set_allocated_description(::google::protobuf::StringValue* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.description_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.description_ = reinterpret_cast<::google::protobuf::StringValue*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.description)
}

// .cusf.common.v1.ConsensusHex hash_id_1 = 3 [json_name = "hashId1"];
inline bool SidechainDeclaration_V0::has_hash_id_1() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.hash_id_1_ != nullptr);
  return value;
}
inline const ::cusf::common::v1::ConsensusHex& SidechainDeclaration_V0::_internal_hash_id_1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::cusf::common::v1::ConsensusHex* p = _impl_.hash_id_1_;
  return p != nullptr ? *p : reinterpret_cast<const ::cusf::common::v1::ConsensusHex&>(::cusf::common::v1::_ConsensusHex_default_instance_);
}
inline const ::cusf::common::v1::ConsensusHex& SidechainDeclaration_V0::hash_id_1() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_1)
  return _internal_hash_id_1();
}
inline void SidechainDeclaration_V0::unsafe_arena_set_allocated_hash_id_1(
    ::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hash_id_1_);
  }
  _impl_.hash_id_1_ = reinterpret_cast<::cusf::common::v1::ConsensusHex*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_1)
}
inline ::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE SidechainDeclaration_V0::release_hash_id_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::cusf::common::v1::ConsensusHex* released = _impl_.hash_id_1_;
  _impl_.hash_id_1_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE SidechainDeclaration_V0::unsafe_arena_release_hash_id_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_1)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::cusf::common::v1::ConsensusHex* temp = _impl_.hash_id_1_;
  _impl_.hash_id_1_ = nullptr;
  return temp;
}
inline ::cusf::common::v1::ConsensusHex* PROTOBUF_NONNULL SidechainDeclaration_V0::_internal_mutable_hash_id_1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hash_id_1_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::cusf::common::v1::ConsensusHex>(GetArena());
    _impl_.hash_id_1_ = reinterpret_cast<::cusf::common::v1::ConsensusHex*>(p);
  }
  return _impl_.hash_id_1_;
}
inline ::cusf::common::v1::ConsensusHex* PROTOBUF_NONNULL SidechainDeclaration_V0::mutable_hash_id_1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::cusf::common::v1::ConsensusHex* _msg = _internal_mutable_hash_id_1();
  // @@protoc_insertion_point(field_mutable:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_1)
  return _msg;
}
inline void SidechainDeclaration_V0::set_allocated_hash_id_1(::cusf::common::v1::ConsensusHex* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hash_id_1_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.hash_id_1_ = reinterpret_cast<::cusf::common::v1::ConsensusHex*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_1)
}

// .cusf.common.v1.Hex hash_id_2 = 4 [json_name = "hashId2"];
inline bool SidechainDeclaration_V0::has_hash_id_2() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.hash_id_2_ != nullptr);
  return value;
}
inline const ::cusf::common::v1::Hex& SidechainDeclaration_V0::_internal_hash_id_2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::cusf::common::v1::Hex* p = _impl_.hash_id_2_;
  return p != nullptr ? *p : reinterpret_cast<const ::cusf::common::v1::Hex&>(::cusf::common::v1::_Hex_default_instance_);
}
inline const ::cusf::common::v1::Hex& SidechainDeclaration_V0::hash_id_2() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_2)
  return _internal_hash_id_2();
}
inline void SidechainDeclaration_V0::unsafe_arena_set_allocated_hash_id_2(
    ::cusf::common::v1::Hex* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hash_id_2_);
  }
  _impl_.hash_id_2_ = reinterpret_cast<::cusf::common::v1::Hex*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_2)
}
inline ::cusf::common::v1::Hex* PROTOBUF_NULLABLE SidechainDeclaration_V0::release_hash_id_2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::cusf::common::v1::Hex* released = _impl_.hash_id_2_;
  _impl_.hash_id_2_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::cusf::common::v1::Hex* PROTOBUF_NULLABLE SidechainDeclaration_V0::unsafe_arena_release_hash_id_2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_2)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::cusf::common::v1::Hex* temp = _impl_.hash_id_2_;
  _impl_.hash_id_2_ = nullptr;
  return temp;
}
inline ::cusf::common::v1::Hex* PROTOBUF_NONNULL SidechainDeclaration_V0::_internal_mutable_hash_id_2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hash_id_2_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::cusf::common::v1::Hex>(GetArena());
    _impl_.hash_id_2_ = reinterpret_cast<::cusf::common::v1::Hex*>(p);
  }
  return _impl_.hash_id_2_;
}
inline ::cusf::common::v1::Hex* PROTOBUF_NONNULL SidechainDeclaration_V0::mutable_hash_id_2()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::cusf::common::v1::Hex* _msg = _internal_mutable_hash_id_2();
  // @@protoc_insertion_point(field_mutable:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_2)
  return _msg;
}
inline void SidechainDeclaration_V0::set_allocated_hash_id_2(::cusf::common::v1::Hex* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.hash_id_2_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.hash_id_2_ = reinterpret_cast<::cusf::common::v1::Hex*>(value);
  // @@protoc_insertion_point(field_set_allocated:cusf.mainchain.v1.SidechainDeclaration.V0.hash_id_2)
}

// -------------------------------------------------------------------

// SidechainDeclaration

// .cusf.mainchain.v1.SidechainDeclaration.V0 v0 = 1 [json_name = "v0"];
inline bool SidechainDeclaration::has_v0() const {
  return sidechain_declaration_case() == kV0;
}
inline bool SidechainDeclaration::_internal_has_v0() const {
  return sidechain_declaration_case() == kV0;
}
inline void SidechainDeclaration::set_has_v0() {
  _impl_._oneof_case_[0] = kV0;
}
inline void SidechainDeclaration::clear_v0() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (sidechain_declaration_case() == kV0) {
    if (GetArena() == nullptr) {
      delete _impl_.sidechain_declaration_.v0_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.sidechain_declaration_.v0_);
    }
    clear_has_sidechain_declaration();
  }
}
inline ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE SidechainDeclaration::release_v0() {
  // @@protoc_insertion_point(field_release:cusf.mainchain.v1.SidechainDeclaration.v0)
  if (sidechain_declaration_case() == kV0) {
    clear_has_sidechain_declaration();
    auto* temp = _impl_.sidechain_declaration_.v0_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.sidechain_declaration_.v0_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::cusf::mainchain::v1::SidechainDeclaration_V0& SidechainDeclaration::_internal_v0() const {
  return sidechain_declaration_case() == kV0 ? *_impl_.sidechain_declaration_.v0_ : reinterpret_cast<::cusf::mainchain::v1::SidechainDeclaration_V0&>(::cusf::mainchain::v1::_SidechainDeclaration_V0_default_instance_);
}
inline const ::cusf::mainchain::v1::SidechainDeclaration_V0& SidechainDeclaration::v0() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cusf.mainchain.v1.SidechainDeclaration.v0)
  return _internal_v0();
}
inline ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE SidechainDeclaration::unsafe_arena_release_v0() {
  // @@protoc_insertion_point(field_unsafe_arena_release:cusf.mainchain.v1.SidechainDeclaration.v0)
  if (sidechain_declaration_case() == kV0) {
    clear_has_sidechain_declaration();
    auto* temp = _impl_.sidechain_declaration_.v0_;
    _impl_.sidechain_declaration_.v0_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SidechainDeclaration::unsafe_arena_set_allocated_v0(
    ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_sidechain_declaration();
  if (value) {
    set_has_v0();
    _impl_.sidechain_declaration_.v0_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cusf.mainchain.v1.SidechainDeclaration.v0)
}
inline ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NONNULL SidechainDeclaration::_internal_mutable_v0() {
  if (sidechain_declaration_case() != kV0) {
    clear_sidechain_declaration();
    set_has_v0();
    _impl_.sidechain_declaration_.v0_ = 
        ::google::protobuf::Message::DefaultConstruct<::cusf::mainchain::v1::SidechainDeclaration_V0>(GetArena());
  }
  return _impl_.sidechain_declaration_.v0_;
}
inline ::cusf::mainchain::v1::SidechainDeclaration_V0* PROTOBUF_NONNULL SidechainDeclaration::mutable_v0()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::cusf::mainchain::v1::SidechainDeclaration_V0* _msg = _internal_mutable_v0();
  // @@protoc_insertion_point(field_mutable:cusf.mainchain.v1.SidechainDeclaration.v0)
  return _msg;
}

inline bool SidechainDeclaration::has_sidechain_declaration() const {
  return sidechain_declaration_case() != SIDECHAIN_DECLARATION_NOT_SET;
}
inline void SidechainDeclaration::clear_has_sidechain_declaration() {
  _impl_._oneof_case_[0] = SIDECHAIN_DECLARATION_NOT_SET;
}
inline SidechainDeclaration::SidechainDeclarationCase SidechainDeclaration::sidechain_declaration_case() const {
  return SidechainDeclaration::SidechainDeclarationCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace mainchain
}  // namespace cusf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cusf_2fmainchain_2fv1_2fcommon_2eproto_2epb_2eh
